### ISSUE TITLE
Rette feil/mangler i henhold til krav i navikt/utvikling (funnet av roboten repo-linter)

### ISSUE THREAD

**Issue by eirslett** [navikt/syfosminfotrygd#1]
Dette er en autogenerert issue, laget av et skript som går gjennom alle NAV sine kodebaser på Github og gjør diverse sjekker. Her er en liste over ting som må endres.

### Beskrivelse mangler

På Github kan man gi hver kodebase en kort beskrivelse. Denne bør fortelle hva kodebasen heter, og litt om hva den brukes til. (Eksempel: kodebasen "veilarbportefoljeflatefs" har beskrivelse "Oversikt for veiledere over oppfølgingsbrukere".)
NB! Dette gjelder ikke beskrivelse i en README-fil, det gjelder beskrivelse i metadataen til selve Github-repoet.
    

Når alle endringer er gjort, så kan denne saken lukkes.

### Jeg har meninger om disse rådene - kan jeg komme med tilbakemeldinger?

Skriv i vei, på Slack-kanalen #open-source.

### Kodebasen vår er ikke open source, derfor er det ikke noe poeng

Selv om koden i dag ikke er åpen for innsyn, så ta høyde for at den kan komme til å bli det i fremtiden. Uansett så vil forbedringene være til hjelp, enten kodebasen er åpen eller ei!

### Hvem har ansvaret for å fikse det her?

Det er i utgangspunktet den/de/teamet som eier kodebasen som må fikse.

### Det er en feil i rådene

Alle roboter gjør jo feil, denne også. Lag en issue på [https://github.com/navikt/repo-linter](https://github.com/navikt/repo-linter).

**Comment by eirslett** [comment]
Minner om denne saka, som framleis ikkje er løyst. Hei @TheUnnamedDude, i fylgje robotanalysa var det du som gjorde [siste commit](https://github.com/navikt/syfosminfotrygd/commit/2226c0408a5af2742a24d9d9b68bf79a1a957c7e) i denne kodebasen, for 8 dager sidan. Kan du fylgje opp denne, eller tagge nokon andre som har eigarskap til koden?

**Comment by eirslett** [comment]
Minner om denne saka, som framleis ikkje er løyst. Hei @MikAoJk, i fylgje robotanalysa var det du som gjorde [siste commit](https://github.com/navikt/syfosminfotrygd/commit/e2f0eeef2587834c5f9eb939035b4939fdbc334b) i denne kodebasen, for 35 minutt sidan. Kan du fylgje opp denne, eller tagge nokon andre som har eigarskap til koden?

**Comment by eirslett** [comment]
Minner om denne saka, som framleis ikkje er løyst. Hei @MikAoJk, i fylgje robotanalysa var det du som gjorde [siste commit](https://github.com/navikt/syfosminfotrygd/commit/258c1ae13c338e35a12ae8be07d854072bd48b94) i denne kodebasen, for 4 dagar sidan. Kan du fylgje opp denne, eller tagge nokon andre som har eigarskap til koden?

**Comment by MikAoJk** [comment]
@TheUnnamedDude plx add description
